; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 4
; RUN: opt < %s -passes=pgo-icall-prom -S | FileCheck %s --check-prefix=ICALL-PROM
; RUN: opt < %s -passes=pgo-icall-prom -enable-vtable-cmp -S | FileCheck %s --check-prefix=ICALL-PROM
; RUN: opt < %s -passes=pgo-icall-prom -enable-vtable-cmp -S -icp-vtable-cmp-inst-threshold=5 -icp-vtable-cmp-inst-last-candidate-threshold=5 -icp-vtable-cmp-total-inst-threshold=5 | FileCheck %s --check-prefix=ICALL-VTABLE

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@_ZTV5Base1 = constant { [4 x ptr] } { [4 x ptr] [ptr null, ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev] }, !type !15
@_ZTV8Derived1 = constant { [4 x ptr], [3 x ptr] } { [4 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev], [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base25func2Ev] }, !type !16, !type !17, !type !18
@_ZTV5Base2 = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base25func2Ev] }, !type !17
@_ZTV8Derived2 = constant { [3 x ptr], [3 x ptr], [4 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base35func3Ev], [3 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr null, ptr @_ZN5Base25func2Ev], [4 x ptr] [ptr inttoptr (i64 -16 to ptr), ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev] }, !type !19, !type !20, !type !21, !type !22
@_ZTV5Base3 = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base35func3Ev] }, !type !21

; Indirect call has one function candidate. The vtable profiles show the function
; might come from three vtables, and these three vtables have two different offsets.
;.
; ICALL-PROM: @_ZTV5Base1 = constant { [4 x ptr] } { [4 x ptr] [ptr null, ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev] }, !type [[META0:![0-9]+]]
; ICALL-PROM: @_ZTV8Derived1 = constant { [4 x ptr], [3 x ptr] } { [4 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev], [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base25func2Ev] }, !type [[META0]], !type [[META1:![0-9]+]], !type [[META2:![0-9]+]]
; ICALL-PROM: @_ZTV5Base2 = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base25func2Ev] }, !type [[META1]]
; ICALL-PROM: @_ZTV8Derived2 = constant { [3 x ptr], [3 x ptr], [4 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base35func3Ev], [3 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr null, ptr @_ZN5Base25func2Ev], [4 x ptr] [ptr inttoptr (i64 -16 to ptr), ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev] }, !type [[META3:![0-9]+]], !type [[META4:![0-9]+]], !type [[META5:![0-9]+]], !type [[META6:![0-9]+]]
; ICALL-PROM: @_ZTV5Base3 = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base35func3Ev] }, !type [[META5]]
;.
; ICALL-VTABLE: @_ZTV5Base1 = constant { [4 x ptr] } { [4 x ptr] [ptr null, ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev] }, !type [[META0:![0-9]+]]
; ICALL-VTABLE: @_ZTV8Derived1 = constant { [4 x ptr], [3 x ptr] } { [4 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev], [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base25func2Ev] }, !type [[META0]], !type [[META1:![0-9]+]], !type [[META2:![0-9]+]]
; ICALL-VTABLE: @_ZTV5Base2 = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base25func2Ev] }, !type [[META1]]
; ICALL-VTABLE: @_ZTV8Derived2 = constant { [3 x ptr], [3 x ptr], [4 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base35func3Ev], [3 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr null, ptr @_ZN5Base25func2Ev], [4 x ptr] [ptr inttoptr (i64 -16 to ptr), ptr null, ptr @_ZN5Base15func0Ev, ptr @_ZN5Base15func1Ev] }, !type [[META3:![0-9]+]], !type [[META4:![0-9]+]], !type [[META5:![0-9]+]], !type [[META6:![0-9]+]]
; ICALL-VTABLE: @_ZTV5Base3 = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN5Base35func3Ev] }, !type [[META5]]
; ICALL-VTABLE: @_ZTV8Derived1.icp.16 = alias ptr, getelementptr inbounds ({ [4 x ptr], [3 x ptr] }, ptr @_ZTV8Derived1, i32 0, i32 0, i32 2)
; ICALL-VTABLE: @_ZTV8Derived2.icp.64 = alias ptr, getelementptr inbounds ({ [3 x ptr], [3 x ptr], [4 x ptr] }, ptr @_ZTV8Derived2, i32 0, i32 2, i32 2)
; ICALL-VTABLE: @_ZTV5Base1.icp.16 = alias ptr, getelementptr inbounds ({ [4 x ptr] }, ptr @_ZTV5Base1, i32 0, i32 0, i32 2)
;.
define i32 @test_one_function_two_offsets_three_vtables(ptr %d) {
; ICALL-PROM-LABEL: define i32 @test_one_function_two_offsets_three_vtables(
; ICALL-PROM-SAME: ptr [[D:%.*]]) {
; ICALL-PROM-NEXT:  entry:
; ICALL-PROM-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[D]], align 8
; ICALL-PROM-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"_ZTS5Base1")
; ICALL-PROM-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
; ICALL-PROM-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 1
; ICALL-PROM-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VFN]], align 8
; ICALL-PROM-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[TMP1]], @_ZN5Base15func1Ev
; ICALL-PROM-NEXT:    br i1 [[TMP2]], label [[IF_TRUE_DIRECT_TARG:%.*]], label [[IF_FALSE_ORIG_INDIRECT:%.*]], !prof [[PROF21:![0-9]+]]
; ICALL-PROM:       if.true.direct_targ:
; ICALL-PROM-NEXT:    [[TMP3:%.*]] = tail call i32 @_ZN5Base15func1Ev(ptr [[D]])
; ICALL-PROM-NEXT:    br label [[IF_END_ICP:%.*]]
; ICALL-PROM:       if.false.orig_indirect:
; ICALL-PROM-NEXT:    [[CALL:%.*]] = tail call i32 [[TMP1]](ptr [[D]])
; ICALL-PROM-NEXT:    br label [[IF_END_ICP]]
; ICALL-PROM:       if.end.icp:
; ICALL-PROM-NEXT:    [[TMP4:%.*]] = phi i32 [ [[CALL]], [[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP3]], [[IF_TRUE_DIRECT_TARG]] ]
; ICALL-PROM-NEXT:    ret i32 [[TMP4]]
;
; ICALL-VTABLE-LABEL: define i32 @test_one_function_two_offsets_three_vtables(
; ICALL-VTABLE-SAME: ptr [[D:%.*]]) {
; ICALL-VTABLE-NEXT:  entry:
; ICALL-VTABLE-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[D]], align 8
; ICALL-VTABLE-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"_ZTS5Base1")
; ICALL-VTABLE-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
; ICALL-VTABLE-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[VTABLE]], @_ZTV8Derived1.icp.16
; ICALL-VTABLE-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[VTABLE]], @_ZTV8Derived2.icp.64
; ICALL-VTABLE-NEXT:    [[TMP3:%.*]] = icmp eq ptr [[VTABLE]], @_ZTV5Base1.icp.16
; ICALL-VTABLE-NEXT:    [[ICMP_OR:%.*]] = or i1 [[TMP1]], [[TMP2]]
; ICALL-VTABLE-NEXT:    [[ICMP_OR1:%.*]] = or i1 [[ICMP_OR]], [[TMP3]]
; ICALL-VTABLE-NEXT:    br i1 [[ICMP_OR1]], label [[IF_THEN_DIRECT_CALL:%.*]], label [[IF_ELSE_ORIG_INDIRECT:%.*]], !prof [[PROF21:![0-9]+]]
; ICALL-VTABLE:       if.then.direct_call:
; ICALL-VTABLE-NEXT:    [[TMP4:%.*]] = tail call i32 @_ZN5Base15func1Ev(ptr [[D]])
; ICALL-VTABLE-NEXT:    br label [[IF_END_ICP:%.*]]
; ICALL-VTABLE:       if.else.orig_indirect:
; ICALL-VTABLE-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 1
; ICALL-VTABLE-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[VFN]], align 8
; ICALL-VTABLE-NEXT:    [[CALL:%.*]] = tail call i32 [[TMP5]](ptr [[D]])
; ICALL-VTABLE-NEXT:    br label [[IF_END_ICP]]
; ICALL-VTABLE:       if.end.icp:
; ICALL-VTABLE-NEXT:    [[TMP6:%.*]] = phi i32 [ [[CALL]], [[IF_ELSE_ORIG_INDIRECT]] ], [ [[TMP4]], [[IF_THEN_DIRECT_CALL]] ]
; ICALL-VTABLE-NEXT:    ret i32 [[TMP6]]
;
entry:
  %vtable = load ptr, ptr %d, !prof !23
  %0 = tail call i1 @llvm.type.test(ptr %vtable, metadata !"_ZTS5Base1")
  tail call void @llvm.assume(i1 %0)
  %vfn = getelementptr inbounds ptr, ptr %vtable, i64 1
  %1 = load ptr, ptr %vfn
  %call = tail call i32 %1(ptr %d), !prof !24
  ret i32 %call
}

define i32 @_ZN5Base15func1Ev(ptr %this) {
entry:
  ret i32 2
}


declare i1 @llvm.type.test(ptr, metadata)
declare void @llvm.assume(i1)
declare i32 @_ZN5Base25func2Ev(ptr)
declare i32 @_ZN5Base15func0Ev(ptr)
declare void @_ZN5Base35func3Ev(ptr)


!llvm.module.flags = !{!1}

!1 = !{i32 1, !"ProfileSummary", !2}
!2 = !{!3, !4, !5, !6, !7, !8, !9, !10}
!3 = !{!"ProfileFormat", !"InstrProf"}
!4 = !{!"TotalCount", i64 10000}
!5 = !{!"MaxCount", i64 200}
!6 = !{!"MaxInternalCount", i64 200}
!7 = !{!"MaxFunctionCount", i64 200}
!8 = !{!"NumCounts", i64 3}
!9 = !{!"NumFunctions", i64 3}
!10 = !{!"DetailedSummary", !11}
!11 = !{!12, !13, !14}
!12 = !{i32 10000, i64 100, i32 1}
!13 = !{i32 990000, i64 100, i32 1}
!14 = !{i32 999999, i64 1, i32 2}
!15 = !{i64 16, !"_ZTS5Base1"}
!16 = !{i64 16, !"_ZTS5Base1"}
!17 = !{i64 48, !"_ZTS5Base2"}
!18 = !{i64 16, !"_ZTS8Derived1"}
!19 = !{i64 64, !"_ZTS5Base1"}
!20 = !{i64 40, !"_ZTS5Base2"}
!21 = !{i64 16, !"_ZTS5Base3"}
!22 = !{i64 16, !"_ZTS8Derived2"}
!23 = !{!"VP", i32 2, i64 1600, i64 -9064381665493407289, i64 800, i64 5035968517245772950, i64 500, i64 3215870116411581797, i64 300}
!24 = !{!"VP", i32 0, i64 1600, i64 6804820478065511155, i64 1600}
